# Dataset V2

input_dir: /Users/simon/Documents/Studium/BP/Datasets/PL3D_test
output_dir: /Users/simon/Documents/Studium/BP/Datasets/PL3D_test_processed
cluster:
  "0":
    [
      "3020300xx",
      "3020301xx",
      "3020302xx",
      "3020303xx",
      "3020304xx",
      "3020306xx",
      "3020307xx",
    ]
  "1": ["2020200xx", "2020300xx", "2020400xx", "2020500xx", "2020600xx"]
  "2": ["203000000"]
  "3": ["3020204xx"]
  "4": ["3020205xx"]
  "5": ["303040xxx"]
  "6": ["304020000", "304050000"]
scalar_field: class
rename: classification
default_class: ~
