input_dir: /SCB/Datasets/villevite_synth
output_dir: /SCB/Datasets/villevite_synth_processed
cluster:
  '0': ['0']
  '1': ['4', '5']
  '2': ['6']
  '3': ['1', '2']
  '4': ['3']
  '5': ['7']
  '6': ['8']
  '7': ['9']
  '8': ['10', '11', '12']
  '9': ['13']
scalar_field: MaterialID
rename: classification
default_class: ~