# Dataset V2

input_dir: /Users/simon/Documents/Studium/BP/Datasets/villevite_synth_test
output_dir: /Users/simon/Documents/Studium/BP/Datasets/villevite_synth_test_processed
cluster:
  "0": ["0"]
  "1": ["3", "4", "5", "6"]
  "2": ["1", "2"]
  "3": ["7"]
  "4": ["8"]
  "5": ["9"]
  "6": ["10", "11", "12"]
scalar_field: MaterialID
rename: classification
default_class: ~
